export const GET_COUNTRIES = "GET_COUNTRIES";
export const COUNTRIES_ERROR = "COUNTRIES_ERROR";
export const GET_COUNTRY_DETAILS = "GET_COUNTRY_DETAILS";
export const GET_COUNTRY_DETAILS_ERROR = "GET_COUNTRY_DETAILS_ERROR";
