export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_DETAILS = "GET_COUNTRY_DETAILS";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const FILTRAR_POR_CONTINENTE = "FILTRAR_POR_CONTINENTE";
export const SORT = "SORT";
